### ISSUE TITLE
recommend

### ISSUE THREAD

**Issue by SOULSAGA777** [naganeko/naganeko.github.io#1]
hope to support select skin

**Comment by naganeko** [comment]
for spine-gif ?

**Comment by SOULSAGA777** [comment]
> for spine-gif ?yes

**Comment by SOULSAGA777** [comment]
* { font-size: 13px; font-family: 'MS Pゴシック', sans-serif;}p, ul, ol, blockquote { margin: 0;}a { color: #0064c8; text-decoration: none;}a:hover { color: #0057af; text-decoration: underline;}a:active { color: #004c98;}



----- Original Message -----




From: "naganeko" ***@***.***>

To: "naganeko/naganeko.github.io" ***@***.***>

Cc: "SOULSAGA777" ***@***.***>; "Author" ***@***.***>

Date: 2022/01/24 月 20:18

Subject: Re: [naganeko/naganeko.github.io] recommend (Issue #1)







for spine-gif ?

yes

sage ID: ***@***.***>

**Comment by naganeko** [comment]
let me have some time to perform this update

**Comment by naganeko** [comment]
@SOULSAGA777 could you send me Spine 2.1 files having multiple skins if you have some?

**Comment by SOULSAGA777** [comment]
https://mega.nz/file/qBpyjLQI#Nh9CDgZ3QY2sIfiwwVJNefoKLDv0RydBcIVMTrzQwVQ

**Comment by naganeko** [comment]
@SOULSAGA777  I updated spine-gif.  test it with your file
https://twitter.com/lazy_schemer/status/1495411110622953478

**Comment by SOULSAGA777** [comment]
Thank you very much
