### ISSUE TITLE
This spine anime is incorrect

### ISSUE THREAD

**Issue by SOULSAGA777** [naganeko/naganeko.github.io#2]
by spine2.1
https://mega.nz/file/vApxkSSS#k6Mya9uIyrq5rpOgS8zJWEsdBCrid3PsizTAxq6ZyJ0

**Comment by naganeko** [comment]
@SOULSAGA777 do you have the original .skel file?

**Comment by SOULSAGA777** [comment]
https://mega.nz/file/uVoViKpJ#PUceu36P7GcB7yfi7Jxr_m1m6MHkrbdmSy_HK8qgPvM

**Comment by naganeko** [comment]
sorry I can't handle this issue.
<img width="555" alt="spine21error" src="https://user-images.githubusercontent.com/57881773/154987351-30ca1ff9-a77b-448e-a5d8-f89c29599c51.png">
even Spine 2.1 cannot import your data.

**Comment by SOULSAGA777** [comment]
![1YH5YI~4MMWQKX$I1E``}R8](https://user-images.githubusercontent.com/98262960/155088473-54763bc7-e0c7-4f71-b56e-72dc66ff7659.png)
SkeletonViewer import
