### ISSUE TITLE
make a script to convert skel to json localization

### ISSUE THREAD

**Issue by SOULSAGA777** [naganeko/naganeko.github.io#3]
make a script to convert skel to json localization

**Comment by naganeko** [comment]
sorry, I didn't catch what you mean . do you need a Japanese or Chinese page of spine-gif?

**Comment by SOULSAGA777** [comment]
ICan you make a conversion tool or script to Convert .skel to .json files？Whether it is the same version conversion or  to 3.8 version.

**Comment by naganeko** [comment]
<img width="589" alt="export" src="https://user-images.githubusercontent.com/57881773/154989683-8565055b-9940-4047-8205-b5a144b0cd7a.png">
the functions are already there.

**Comment by SOULSAGA777** [comment]
Yeah, I know. So I'm talking about localization, I mean batch processing locally, directly selecting folders or dragging and dropping files for batch conversion, instead of going to the web page to load and export each one. Can you make a .py or .bat or .bms or .exe tool to convert them. Of course, you can also put the batch function in the web page, I just want to batch it.

**Comment by naganeko** [comment]
for some legal issues , I can open the web version only 🤐 sorry

**Comment by SOULSAGA777** [comment]
Please add batch function for web thank you！
